{
 "title": "Main",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Current Passing Resources by Platform and Severity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Passing GCP Counts by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"passed\",platform=\"gcp\"}) by (control_id))",
     "legendFormat": "High Passing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"passed\",platform=\"gcp\"}) by (control_id))",
     "legendFormat": "Medium Passing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"passed\",platform=\"gcp\"}) by (control_id))",
     "legendFormat": "Low Passing Resources"
    }
   ]
  },
  {
   "title": "Passing Kubernetes Counts by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"passed\",platform=\"kubernetes\"}) by (control_id))",
     "legendFormat": "High Passing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"passed\",platform=\"kubernetes\"}) by (control_id))",
     "legendFormat": "Medium Passing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"passed\",platform=\"kubernetes\"}) by (control_id))",
     "legendFormat": "Low Passing Resources"
    }
   ]
  },
  {
   "title": "Passing AWS Counts by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"passed\",platform=\"aws\"}) by (control_id))",
     "legendFormat": "High Passing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"passed\",platform=\"aws\"}) by (control_id))",
     "legendFormat": "Medium Passing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"passed\",platform=\"aws\"}) by (control_id))",
     "legendFormat": "Low Passing Resources"
    }
   ]
  },
  { "title": "Passing by Severity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Overall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"passed\"}) by (control_id))",
     "legendFormat": "High Risk Passing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"failed\"}) by (control_id))",
     "legendFormat": "Medium Risk Passing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"passed\"}) by (control_id))",
     "legendFormat": "Low Risk Passing Resources"
    }
   ]
  },
  {
   "title": "High",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"passed\"}) by (control_id))",
     "legendFormat": "High Risk Passing Resources"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"passed\"}) by (control_id))",
     "legendFormat": "Medium Risk Passing Resources"
    }
   ]
  },
  {
   "title": "Low",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"passed\"}) by (control_id))",
     "legendFormat": "Low Risk Passing Resources"
    }
   ]
  },
  {
   "title": "Current Failing Resources by Platform and Severity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Failing GCP Counts by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"failed\",platform=\"gcp\"}) by (control_id))",
     "legendFormat": "High Failing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"failed\",platform=\"gcp\"}) by (control_id))",
     "legendFormat": "Medium Failing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"failed\",platform=\"gcp\"}) by (control_id))",
     "legendFormat": "Low Failing Resources"
    }
   ]
  },
  {
   "title": "Failing K8s Counts by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"failed\",platform=\"kubernetes\"}) by (control_id))",
     "legendFormat": "High Failing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"failed\",platform=\"kubernetes\"}) by (control_id))",
     "legendFormat": "Medium Failing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"failed\",platform=\"kubernetes\"}) by (control_id))",
     "legendFormat": "Low Failing Resources"
    }
   ]
  },
  {
   "title": "Failing AWS Counts by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"failed\",platform=\"aws\"}) by (control_id))",
     "legendFormat": "High Failing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"failed\",platform=\"aws\"}) by (control_id))",
     "legendFormat": "Medium Failing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"failed\",platform=\"aws\"}) by (control_id))",
     "legendFormat": "Low Failing Resources"
    }
   ]
  },
  { "title": "Failing by Severity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Overall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"failed\"}) by (control_id))",
     "legendFormat": "High Failing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"failed\"}) by (control_id))",
     "legendFormat": "Medium Failing Resources"
    },
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"failed\"}) by (control_id))",
     "legendFormat": "Low Failing Resources"
    }
   ]
  },
  {
   "title": "High",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"7|8|9|10\",status=\"failed\"}) by (control_id))",
     "legendFormat": "High Failing Resources"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"4|5|6\",status=\"failed\"}) by (control_id))",
     "legendFormat": "Medium Failing Resources"
    }
   ]
  },
  {
   "title": "Low",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count (opencspm_resource_export{severity=~\"1|2|3\",status=\"failed\"}) by (control_id))",
     "legendFormat": "Low Failing Resources"
    }
   ]
  }
 ]
}